package com.example.ui.components

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.widget.Toast
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ContentCopy
import androidx.compose.material.icons.filled.Share
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.Icon
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.data.model.TeamLeaderboardEntry
import com.example.data.model.Tournament
import com.example.ui.theme.EsportsCyan
import com.example.ui.theme.EsportsSurface
import com.example.ui.theme.EsportsSurfaceVariant
import com.example.ui.theme.EsportsTextPrimary
import com.example.ui.theme.EsportsTextSecondary

@Composable
fun ShareSummaryDialog(
    tournament: Tournament?,
    leaderboard: List<TeamLeaderboardEntry>,
    onDismiss: () -> Unit
) {
    val context = LocalContext.current
    val tourneyName = tournament?.name ?: "Esports Tournament"
    val gameTitle = tournament?.gameTitle ?: "Free Fire"

    val summaryText = buildString {
        appendLine("🏆 $tourneyName ($gameTitle) 🏆")
        appendLine("Official Leaderboard Standings:")
        appendLine("--------------------------------------")
        leaderboard.take(16).forEach { entry ->
            val crown = if (entry.rank == 1) "👑 " else "${entry.rank}. "
            val tag = entry.team.tag.padEnd(6)
            appendLine("$crown$tag | ${entry.totalPoints} PTS | ${entry.booyahCount} Booyah | ${entry.totalKills} Kills")
        }
        appendLine("--------------------------------------")
        appendLine("Generated by Esports Scoreboard Hub")
    }

    AlertDialog(
        onDismissRequest = onDismiss,
        containerColor = EsportsSurface,
        shape = RoundedCornerShape(16.dp),
        icon = {
            Icon(
                imageVector = Icons.Default.Share,
                contentDescription = "Share",
                tint = EsportsCyan
            )
        },
        title = {
            Text(
                text = "Export Standings Summary",
                color = EsportsTextPrimary,
                fontWeight = FontWeight.Bold,
                fontSize = 18.sp
            )
        },
        text = {
            Column(
                modifier = Modifier
                    .fillMaxWidth()
                    .height(260.dp)
                    .background(EsportsSurfaceVariant, RoundedCornerShape(8.dp))
                    .padding(12.dp)
                    .verticalScroll(rememberScrollState())
            ) {
                Text(
                    text = summaryText,
                    color = EsportsTextPrimary,
                    fontSize = 12.sp,
                    fontFamily = FontFamily.Monospace
                )
            }
        },
        confirmButton = {
            Button(
                onClick = {
                    val clipboard = context.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
                    val clip = ClipData.newPlainText("Tournament Standings", summaryText)
                    clipboard.setPrimaryClip(clip)
                    Toast.makeText(context, "Copied standings to clipboard!", Toast.LENGTH_SHORT).show()
                    onDismiss()
                },
                colors = ButtonDefaults.buttonColors(
                    containerColor = EsportsCyan,
                    contentColor = Color(0xFF381E72)
                ),
                shape = RoundedCornerShape(8.dp),
                modifier = Modifier.testTag("copy_summary_btn")
            ) {
                Icon(
                    imageVector = Icons.Default.ContentCopy,
                    contentDescription = "Copy",
                    modifier = Modifier.height(16.dp)
                )
                Spacer(modifier = Modifier.width(6.dp))
                Text("Copy Summary", fontWeight = FontWeight.Bold)
            }
        },
        dismissButton = {
            OutlinedButton(
                onClick = onDismiss,
                shape = RoundedCornerShape(8.dp)
            ) {
                Text("Close", color = EsportsTextSecondary)
            }
        }
    )
}
